# Generated by Django 5.2.2 on 2025-07-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0003_alter_historiquepersonnel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_salle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHospitalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('est_occupe', models.BooleanField(default=False)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='administration.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('en panne', 'En panne'), ('maintenance', 'Maintenance')], default='fonctionnel', max_length=50)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='administration.salle')),
            ],
        ),
        migrations.AddField(
            model_name='salle',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='administration.servicehospitalier'),
        ),
        migrations.CreateModel(
            name='AffectationPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnelmedical')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.servicehospitalier')),
            ],
        ),
    ]
