# Generated by Django 5.2.2 on 2025-07-16 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0002_historiquesoin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_enregistres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soin',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_realises', to=settings.AUTH_USER_MODEL),
        ),
    ]
