# Generated by Django 5.2.4 on 2025-07-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('pharmacien', 'Pharmacien'), ('laborantin', 'Laborantin'), ('imagerie', 'Technicien Imagerie')], max_length=20)),
                ('date_embauche', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
