# Generated by Django 5.2.2 on 2025-07-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_historiquepersonnel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquepersonnel',
            options={'verbose_name': 'Historique personnel', 'verbose_name_plural': 'Historiques personnel'},
        ),
        migrations.AlterModelOptions(
            name='personnelmedical',
            options={'verbose_name': 'Personnel médical', 'verbose_name_plural': 'Personnel médical'},
        ),
        migrations.AlterField(
            model_name='personnelmedical',
            name='role',
            field=models.CharField(choices=[('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('pharmacien', 'Pharmacien'), ('laborantin', 'Laborantin'), ('imagerie', 'Technicien Imagerie'), ('chirurgien', 'Chirurgien'), ('anesthesiste', 'Anesthésiste')], max_length=20),
        ),
    ]
