# Generated by Django 5.2.4 on 2025-07-11 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0008_ordonnance_assurance_ordonnance_prise_en_charge'),
        ('patients', '0005_historiquepatient_delete_patientlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('en cours', 'En cours'), ('terminée', 'Terminée')], default='en attente', max_length=20)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.patient')),
                ('prescripteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_analyse', to=settings.AUTH_USER_MODEL)),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.typeanalyse')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField()),
                ('date_resultat', models.DateTimeField(auto_now_add=True)),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='laboratoire.analysebiologique')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
