# Generated by Django 5.2.2 on 2025-07-12 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_ordonnance_assurance_ordonnance_prise_en_charge'),
        ('laboratoire', '0002_historiqueanalyse'),
        ('patients', '0005_historiquepatient_delete_patientlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysebiologique',
            old_name='date_demande',
            new_name='date_prescription',
        ),
        migrations.RemoveField(
            model_name='analysebiologique',
            name='prescripteur',
        ),
        migrations.AddField(
            model_name='analysebiologique',
            name='autre_type_analyse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analysebiologique',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('terminee', 'Terminée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='type_analyse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.typeanalyse'),
        ),
    ]
