# Generated by Django 5.2.2 on 2025-07-12 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0003_rename_date_demande_analysebiologique_date_prescription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysebiologique',
            name='prescripteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_prescrites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_enregistrees', to=settings.AUTH_USER_MODEL),
        ),
    ]
