# Generated by Django 5.2.2 on 2025-07-12 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_prescriptionanalyse'),
        ('laboratoire', '0004_analysebiologique_prescripteur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysebiologique',
            name='statut',
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='autre_type_analyse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='prescripteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_prescrites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
