# Generated by Django 5.2.2 on 2025-07-12 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0005_remove_analysebiologique_statut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultatanalyse',
            old_name='valeur',
            new_name='contenu',
        ),
        migrations.RemoveField(
            model_name='resultatanalyse',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='analysebiologique',
            name='date_demande',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='date_prescription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='type_analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.typeanalyse'),
        ),
        migrations.AlterField(
            model_name='resultatanalyse',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='laboratoire.analysebiologique'),
        ),
        migrations.AlterField(
            model_name='resultatanalyse',
            name='date_resultat',
            field=models.DateField(auto_now_add=True),
        ),
    ]
