# Generated by Django 5.2.2 on 2025-07-10 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_historiquepatient_delete_patientlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('AMO', 'AMO'), ('PRIVEE', 'Privée')], max_length=50)),
                ('couverture', models.DecimalField(decimal_places=2, help_text='Pourcentage de prise en charge (ex: 80%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=100)),
                ('date_expiration', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurances.assurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_approuve', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=50)),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurances.assurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
