# Generated by Django 5.2.2 on 2025-07-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_dossiermedical'),
        ('patients', '0005_historiquepatient_delete_patientlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossiermedical',
            old_name='notes_supplementaires',
            new_name='autres_infos',
        ),
        migrations.RenameField(
            model_name='dossiermedical',
            old_name='traitements_chroniques',
            new_name='traitements_en_cours',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
