# Generated by Django 5.2.2 on 2025-07-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rename_notes_supplementaires_dossiermedical_autres_infos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date_consultation']},
        ),
    ]
