# Generated by Django 5.2.2 on 2025-07-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_consultation_options'),
        ('pharmacie', '0002_historiquemedicament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_assurance', models.CharField(choices=[('classique', 'Classique'), ('amo', 'Assurance Maladie Obligatoire (AMO)'), ('nsia assurances', 'Nsia assurances'), ('sabuyuman', 'Sabuyuman'), ('autres', 'Autres')], default='classique', max_length=50)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('posologie', models.TextField()),
                ('duree', models.CharField(max_length=100)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='consultations.ordonnance')),
            ],
        ),
    ]
