# Generated by Django 5.2.2 on 2025-07-12 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_ordonnance_assurance_ordonnance_prise_en_charge'),
        ('laboratoire', '0004_analysebiologique_prescripteur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autre_type_analyse', models.CharField(blank=True, max_length=255, null=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_analyse', to='consultations.consultation')),
                ('prescripteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.typeanalyse')),
            ],
        ),
    ]
