# Generated by Django 5.2.2 on 2025-07-13 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_historiquepatient_delete_patientlog'),
        ('personnel', '0003_alter_historiquepersonnel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionChirurgicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'intervention")),
                ('heure_intervention', models.TimeField(default=django.utils.timezone.now, verbose_name="Heure d'intervention")),
                ('type_intervention', models.CharField(max_length=200, verbose_name="Type d'intervention")),
                ('salle', models.CharField(max_length=100, verbose_name="Salle d'opération")),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu opératoire')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('anesthesiste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_anesthesiste', to='personnel.personnelmedical', verbose_name='Anesthésiste')),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_chirurgien', to='personnel.personnelmedical', verbose_name='Chirurgien principal')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Intervention chirurgicale',
                'verbose_name_plural': 'Interventions chirurgicales',
                'ordering': ['-date_intervention', '-heure_intervention'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=100, verbose_name='Action effectuée')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='bloc_operatoire.interventionchirurgicale', verbose_name='Intervention')),
            ],
            options={
                'verbose_name': "Historique d'intervention",
                'verbose_name_plural': "Historiques d'interventions",
                'ordering': ['-date_action'],
            },
        ),
    ]
