# Generated by Django 5.2.2 on 2025-07-13 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc_operatoire', '0001_initial'),
        ('patients', '0005_historiquepatient_delete_patientlog'),
        ('personnel', '0003_alter_historiquepersonnel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionchirurgicale',
            name='anesthesiste',
        ),
        migrations.RemoveField(
            model_name='interventionchirurgicale',
            name='chirurgien',
        ),
        migrations.RemoveField(
            model_name='interventionchirurgicale',
            name='patient',
        ),
        migrations.CreateModel(
            name='OperationChirurgicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure de l'opération")),
                ('type_operation', models.CharField(max_length=200, verbose_name="Type d'opération")),
                ('salle', models.CharField(max_length=100, verbose_name="Salle d'opération")),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu opératoire')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('anesthesiste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_anesthesiste', to='personnel.personnelmedical', verbose_name='Anesthésiste')),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_chirurgien', to='personnel.personnelmedical', verbose_name='Chirurgien principal')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Opération chirurgicale',
                'verbose_name_plural': 'Opérations chirurgicales',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=100, verbose_name='Action effectuée')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('details', models.TextField(blank=True, verbose_name='Détails supplémentaires')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='bloc_operatoire.operationchirurgicale', verbose_name='Opération')),
            ],
            options={
                'verbose_name': "Historique d'opération",
                'verbose_name_plural': "Historiques d'opérations",
                'ordering': ['-date_action'],
            },
        ),
        migrations.DeleteModel(
            name='HistoriqueIntervention',
        ),
        migrations.DeleteModel(
            name='InterventionChirurgicale',
        ),
    ]
