# Generated by Django 5.2.2 on 2025-07-16 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assurances', '0002_historiqueassurance'),
        ('bloc_operatoire', '0002_remove_interventionchirurgicale_anesthesiste_and_more'),
        ('consultations', '0010_hospitalisation_utilisateur_and_more'),
        ('imagerie', '0003_examenimagerie_utilisateur_and_more'),
        ('laboratoire', '0007_remplir_date_demande'),
        ('patients', '0005_historiquepatient_delete_patientlog'),
        ('soins', '0003_soin_utilisateur_alter_soin_personnel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('montant_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_patient', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('non payée', 'Non Payée'), ('partiellement payée', 'Partiellement Payée'), ('payée', 'Payée')], default='non payée', max_length=20)),
                ('analyse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.analysebiologique')),
                ('assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurances.assurance')),
                ('hospitalisation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.hospitalisation')),
                ('imagerie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagerie.examenimagerie')),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloc_operatoire.operationchirurgicale')),
                ('ordonnance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.ordonnance')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient', verbose_name='Patient')),
                ('soin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soins.soin')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('espèces', 'Espèces'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('sama_money', 'Sama Money'), ('carte_bancaire', 'Carte Bancaire')], default='espèces', max_length=50)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_remboursement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(max_length=255)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='facturation.paiement')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
