# Generated by Django 5.2.2 on 2025-07-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('urgences', '0002_urgence'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='urgence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urgences.urgence'),
        ),
    ]
