# Generated by Django 5.2.2 on 2025-07-12 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0001_initial'),
        ('patients', '0005_historiquepatient_delete_patientlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueImagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
