# Generated by Django 5.2.2 on 2025-07-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(default='inconnu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(default='Inconnu', max_length=20),
            preserve_default=False,
        ),
    ]
