# Generated by Django 5.2.2 on 2025-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_actif_alter_patient_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_deces',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='signature_deces',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='signature_sortie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('consulté', 'Consulté'), ('hospitalisé', 'Hospitalisé'), ('sorti', 'Sorti'), ('décédé', 'Décédé')], default='consulté', max_length=20),
        ),
    ]
